@extends('layouts.negocios')

@section('content')



    <div class="bg_color_1">
        <div class="container margin_120_95">
            <p>Cap&iacute;tulo I. De las Partes intervinientes y el objeto del tratamiento de la informaci&oacute;n o datos personales</p>
            <p><strong>Responsable o Encargado del tratamiento de informaci&oacute;n o datos personales</strong></p>
            <p>DPSoluciones con NIT 1036933941-1; persona jur&iacute;dica constituida de conformidad con las leyes mercantiles colombianas, con domicilio principal en la ciudad de Rionegro, Antioquia, Colombia Tel: 057- 3207349676, y direcci&oacute;n electr&oacute;nica info@riobooking.co, en adelante Riobooking.</p>
            <p><strong>Usuarios</strong></p>
            <p>Clientes, proveedores, subcontratistas y colaboradores o empleados de RIOBOOKING. que hayan suministrado la informaci&oacute;n o datos personales en virtud del servicio prestado por &eacute;sta, en adelante USUARIO.</p>
            <p><strong>Objeto</strong></p>
            <p>El presente documento tiene por objeto dar cumplimiento a lo previsto en el literal k del art&iacute;culo 17 de la Ley 1581 de 2012, que consiste en la elaboraci&oacute;n y adopci&oacute;n de un manual interno de pol&iacute;ticas y procedimientos para garantizar el adecuado cumplimiento de la ley 1581 de 2012 la cual regula la obtenci&oacute;n, registro, manejo y tratamiento de los datos de car&aacute;cter personal que realiza RIOBOOKING en el ejercicio ordinario de su objeto social, con el fin de garantizar y proteger el derecho fundamental de habeas data de sus usuarios.</p>
            <p>​Cap&iacute;tulo II. Definiciones y Principios</p>
            <p><strong>​Definiciones</strong></p>
            <p>De acuerdo con lo establecido en el art&iacute;culo 3 de la Ley 1581 de 2012 se definen y entienden los siguientes t&eacute;rminos:</p>
            <p><strong>Autorizaci&oacute;n:&nbsp;</strong>Consentimiento previo, expreso e informado del USUARIO para llevar a cabo el Tratamiento de datos personales;</p>
            <p><strong>Aviso de privacidad:</strong>&nbsp;Documento f&iacute;sico, electr&oacute;nico o en cualquier otro formato generado por RIOBOOKING que se pone a disposici&oacute;n del USUARIO para el tratamiento de sus datos personales. En el Aviso de Privacidad se comunica al USUARIO la informaci&oacute;n relativa a la existencia de las pol&iacute;ticas de tratamiento de informaci&oacute;n que le ser&aacute;n aplicables, la forma de acceder a las mismas y las caracter&iacute;sticas del tratamiento que se pretende dar a los datos personales.</p>
            <p><strong>Base de Datos:&nbsp;</strong>Conjunto organizado de datos personales que sean objeto de Tratamiento.</p>
            <p><strong>Dato personal:&nbsp;</strong>Cualquier informaci&oacute;n vinculada o que pueda asociarse a una o varias personas naturales determinadas o determinables.</p>
            <p><strong>Dato privado:&nbsp;</strong>Es el dato que por su naturaleza &iacute;ntima o reservada s&oacute;lo es relevante para el USUARIO.</p>
            <p><strong>Datos sensibles:&nbsp;</strong>Se entiende por datos sensibles aquellos que afectan la intimidad del USUARIO o cuyo uso indebido puede generar su discriminaci&oacute;n, tales como aquellos que revelen el origen racial o &eacute;tnico, la orientaci&oacute;n pol&iacute;tica, las convicciones religiosas o filos&oacute;ficas, la pertenencia a sindicatos, organizaciones sociales, de derechos humanos o que promueva intereses de cualquier partido pol&iacute;tico o que garanticen los derechos y garant&iacute;as de partidos pol&iacute;ticos de oposici&oacute;n, as&iacute; como los datos relativos a la salud, a la vida sexual y los datos biom&eacute;tricos.</p>
            <p><strong>Encargado del Tratamiento:&nbsp;</strong>Persona natural o jur&iacute;dica, p&uacute;blica o privada, que por s&iacute; misma o en asocio con otros, realice el Tratamiento de datos personales por cuenta del Responsable del Tratamiento.</p>
            <p><strong>Responsable del Tratamiento:</strong>&nbsp;Persona natural o jur&iacute;dica, p&uacute;blica o privada, que por s&iacute; misma o en asocio con otros, decida sobre la base de datos y/o el Tratamiento de los datos.</p>
            <p><strong>Usuario:&nbsp;</strong>Persona natural cuyos datos personales sean objeto de Tratamiento.</p>
            <p><strong>Tratamiento:&nbsp;</strong>Cualquier operaci&oacute;n o conjunto de operaciones sobre datos personales, tales como la recolecci&oacute;n, almacenamiento, uso, circulaci&oacute;n o supresi&oacute;n de los mismos.​</p>
            <p><strong>Principios</strong></p>
            <p>Los principios que se establecen a continuaci&oacute;n constituyen los par&aacute;metros generales que RIOBOOKING aplica y salvaguarda en el ejercicio de los procesos de captura, registro, manejo uso y tratamiento de datos personales.</p>
            <p><strong>Principio de legalidad en materia de Tratamiento de datos:</strong>&nbsp;El Tratamiento a que se refiere la ley 1581 de 2012, es una actividad reglada que debe sujetarse a lo establecido en ella y en las dem&aacute;s disposiciones que la desarrollen.</p>
            <p><strong>Principio de finalidad:&nbsp;</strong>El Tratamiento debe obedecer a una finalidad leg&iacute;tima de acuerdo con la Constituci&oacute;n y la Ley, la cual debe ser informada al USUARIO.</p>
            <p><strong>Principio de libertad:&nbsp;</strong>El Tratamiento s&oacute;lo puede ejercerse con el consentimiento previo, expreso e informado del USUARIO. Los datos personales no podr&aacute;n ser obtenidos o divulgados sin previa autorizaci&oacute;n, o en ausencia de mandato legal o judicial que releve el consentimiento.</p>
            <p><strong>Principio de veracidad o calidad:&nbsp;</strong>La informaci&oacute;n sujeta a Tratamiento debe ser veraz, completa, exacta, actualizada, comprobable y comprensible. Se proh&iacute;be el Tratamiento de datos parciales, incompletos, fraccionados o que induzcan a error.</p>
            <p><strong>Principio de transparencia:&nbsp;</strong>En el Tratamiento debe garantizarse el derecho del USUARIO a obtener del Responsable del Tratamiento o del Encargado del Tratamiento, en cualquier momento y sin restricciones, informaci&oacute;n acerca de la existencia de datos que le conciernan.</p>
            <p><strong>Principio de acceso y circulaci&oacute;n restringida:&nbsp;</strong>El Tratamiento se sujeta a los l&iacute;mites que se derivan de la naturaleza de los datos personales, de las disposiciones de la ley 1581 de 2012 y la Constituci&oacute;n. En este sentido, el Tratamiento s&oacute;lo podr&aacute; hacerse por personas autorizadas por el USUARIO y/o por las personas previstas en la Ley 1581 de 2012.</p>
            <p>Los datos personales, salvo la informaci&oacute;n p&uacute;blica, no podr&aacute;n estar disponibles en Internet u otros medios de divulgaci&oacute;n o comunicaci&oacute;n masiva, salvo que el acceso sea t&eacute;cnicamente controlable para brindar un conocimiento restringido s&oacute;lo a los USUARIOS autorizados conforme a la ley 1581 de 2012.</p>
            <p><strong>Principio de seguridad:&nbsp;</strong>La informaci&oacute;n sujeta a Tratamiento por el Responsable del Tratamiento o Encargado del Tratamiento a que se refiere a la ley 1581 de 2012, se deber&aacute; manejar con las medidas t&eacute;cnicas, humanas y administrativas que sean necesarias para otorgar seguridad a los registros evitando su adulteraci&oacute;n, p&eacute;rdida, consulta, uso o acceso no autorizado o fraudulento.</p>
            <p><strong>Principio de confidencialidad:&nbsp;</strong>Todas las personas que intervengan en el Tratamiento de datos personales que no tengan la naturaleza de p&uacute;blicos est&aacute;n obligadas a garantizar la reserva de la informaci&oacute;n, inclusive despu&eacute;s de finalizada su relaci&oacute;n con alguna de las labores que comprende el Tratamiento, pudiendo s&oacute;lo realizar suministro o comunicaci&oacute;n de datos personales cuando ello corresponda al desarrollo de las actividades autorizadas en la ley 1581 de 2012 y en los t&eacute;rminos de la misma.</p>
            <p>Cap&iacute;tulo III. Finalidad y Tratamiento de los datos.</p>
            <p><strong>​Finalidad</strong></p>
            <p>Quien acceda a los servicios de RIOBOOKING debe suministrar de manera voluntaria sus datos ciertos de identificaci&oacute;n f&iacute;sica o personal, como son entre otros: nombre, apellidos, identificaci&oacute;n, edad, g&eacute;nero, tel&eacute;fono, direcci&oacute;n f&iacute;sica y electr&oacute;nica, pa&iacute;s, ciudad y dem&aacute;s datos necesarios que le sean solicitados en el proceso de registro como colaborador, proveedor o cliente de RIOBOOKING.</p>
            <p>Los datos personales proporcionados a RIOBOOKING por los USUARIOS, son captados con la finalidad de:</p>
            <p>​&bull; ​Proveer adecuadamente de los servicios y/o productos contratados con RIOBOOKING</p>
            <p>​&bull; ​Gestionar tr&aacute;mites (PQR)</p>
            <p>​&bull; ​Informar sobre el Estado de los Servicios y/o productos.</p>
            <p>​&bull; ​Realizar an&aacute;lisis de riesgo y verificaci&oacute;n de antecedentes.</p>
            <p>​&bull; ​Efectuar encuestas de satisfacci&oacute;n respecto de los productos y/o servicios de RIOBOOKING</p>
            <p>​&bull; ​Informar sobre nuestros productos, servicios, ofertas, promociones, alianzas, estudios de mercado, concursos, contenidos y otros.</p>
            <p>​&bull; ​Almacenar informaci&oacute;n t&eacute;cnica para el perfilamiento de cada USUARIO de los servicios y/o productos contratados con RIOBOOKING.</p>
            <p>​&bull; ​Compartir, transferir y transmitir los datos personales a terceros en otros pa&iacute;ses para los fines relacionados con la operaci&oacute;n.</p>
            <p>​&bull; ​Consolidar los datos necesarios para la ejecuci&oacute;n del proceso de contrataci&oacute;n de nuevos aspirantes de cargos requeridos dentro de la organizaci&oacute;n.</p>
            <p>​&bull; ​Almacenar y tratar datos biom&eacute;tricos y video de vigilancia para salvaguardar las instalaciones fiscas de la organizaci&oacute;n.</p>
            <p>​&bull; ​Utilizar videos o im&aacute;genes captadas en los eventos donde participa la organizaci&oacute;n para campa&ntilde;as comerciales y soporte de actividades ante terceros.</p>
            <p>​&bull; ​Recopilar los datos requeridos para realizar actividades de bienestar social.</p>
            <p><strong>Tratamiento de los datos</strong></p>
            <p>RIOBOOKING manifiesta ser responsable de los datos personales de sus usuarios siempre que esta informaci&oacute;n le haya sido suministrada por &eacute;stos, al igual que la de la base de datos o medio de almacenamiento donde se encuentren ubicados los mismos y sea de su propiedad o manejo.</p>
            <p><strong>Protecci&oacute;n de la Informaci&oacute;n suministrada</strong></p>
            <p>RIOBOOKING protege a sus USUARIOS del acceso, modificaci&oacute;n, divulgaci&oacute;n o destrucci&oacute;n no autorizada de la informaci&oacute;n registrada en sus bases de datos existentes, por eso la organizaci&oacute;n tiene como manual de buenas practicas la Norma ISO/IEC 27000; esta norma establece la implementaci&oacute;n de directrices y controles t&eacute;cnicos que tienen como objetivo principal la gesti&oacute;n del riesgo tecnol&oacute;gico y la minimizaci&oacute;n del impacto nocivo de estos para misi&oacute;n y visi&oacute;n de RIOBOOKING, y as&iacute; brindar tranquilidad en toda la relaci&oacute;n que se genere entre RIOBOOKING y los USUARIOS.</p>
            <p>RIOBOOKING con el fin de dar cumplimiento a su obligaci&oacute;n de protecci&oacute;n de datos sigue de manera estricta y rigurosa los siguientes protocolos de protecci&oacute;n de datos:</p>
            <p>​&bull; ​Control sobre los sistemas de informaci&oacute;n para mantener su calidad y funcionamiento &oacute;ptimo.</p>
            <p>​&bull; ​Cifrado de servicios usando protocolos de seguridad, restricci&oacute;n de acceso a la informaci&oacute;n de acuerdo a tipo de usuario de la misma.</p>
            <p>​&bull; ​Acuerdos de confidencialidad con todo nuestro personal, subcontratistas o proveedores, para el caso de los colaboradores o empleados de RIOBOOKING la vulneraci&oacute;n de dichos acuerdos constituye falta grave, causal de despido con justa causa y en el caso de los proveedores o subcontratistas implica la terminaci&oacute;n anticipada de contratos o acuerdos, sin menoscabo de las acciones indemnizatorias previstas en la ley 1581 de 2012 y las normas internacionales.</p>
            <p>​&bull; ​Implementaci&oacute;n y mejoramiento de controles en las instalaciones f&iacute;sicas, para proteger los datos que se encuentra contenidos de forma f&iacute;sica, con el fin de mitigar el efecto nocivo que podr&iacute;a originar la materializaci&oacute;n de alg&uacute;n riesgo al que se enfrenta los datos sensibles administrados por RIOBOOKING.</p>
            <p>Est&aacute; expresamente restringida la revelaci&oacute;n de informaci&oacute;n personal de los USUARIOS a terceras personas sin su consentimiento expreso de &eacute;stos.</p>
            <p>Puede haber circunstancias en las que es posible revelar informaci&oacute;n personal sobre un usuario; las razones que da pie a esto son: El empleo de otras empresas para realizar funciones en nuestro nombre, tales como el cumplimiento de pedidos, proporcionar servicio al cliente, env&iacute;o de correo electr&oacute;nico y correspondencia, procesamiento de pagos con tarjeta de cr&eacute;dito, procesamiento de conversiones de moneda, contrataci&oacute;n de servidores ubicados dentro o fuera del Pa&iacute;s (Colombia), u otras funciones necesarias para nuestro negocio. Tambi&eacute;n se podr&aacute; revelar informaci&oacute;n personal cuando sea requerida por una entidad p&uacute;blica o administrativa en ejercicio de sus funciones legales o por orden judicial, para este caso RIOBOOKING notificar&aacute; a los USUARIOS ocho (8) d&iacute;as h&aacute;biles antes de la entrega a la autoridad competente, este deber que asume RIOBOOKING al informar a la otra parte de cualquier requerimiento, hace las veces de notificaci&oacute;n, pero no da facultades para revelar informaci&oacute;n personal.</p>
            <p>En el caso que RIOBOOKING no reciba notificaci&oacute;n de la revocatoria de la autorizaci&oacute;n, este dar&aacute; por hecho la aprobaci&oacute;n para la revelaci&oacute;n de la informaci&oacute;n personal en el momento que sea requerida por una entidad p&uacute;blica o administrativa en ejercicio de sus funciones legales o por orden judicial.</p>
            <p>En caso de una venta de la mayor&iacute;a de los activos de la empresa, la informaci&oacute;n de los clientes y/o usuarios puede ser transferida al comprador como parte del establecimiento de comercio.</p>
            <p><strong>Recepci&oacute;n de informaci&oacute;n de los usuarios y uso</strong></p>
            <p>La informaci&oacute;n privada de los USUARIOS est&aacute; destinada a la prestaci&oacute;n del servicio para desarrollar el objeto social de RIOBOOKING.</p>
            <p>RIOBOOKING puede de forma autom&aacute;tica registrar la informaci&oacute;n del USUARIO en registros de nuestro servidor desde su navegador, incluyendo su direcci&oacute;n IP, la versi&oacute;n de su navegador web, direcciones de referencia entre otros.</p>
            <p>Tambi&eacute;n podemos grabar las visitas que el USUARIO haga a cualquiera de los sitios web o aplicaciones a los cuales ingrese que sean de propiedad de RIOBOOKING.</p>
            <p>Las obligaciones incluidas en estas pr&aacute;cticas sobre el cuidado o manejo que RIOBOOKING le debe dar a la informaci&oacute;n personal de sus USUARIOS no aplican cuando la informaci&oacute;n sea requerida por una entidad p&uacute;blica o administrativa en ejercicio de sus funciones legales o por orden judicial.</p>
            <p><strong>Empleo de rastreo electr&oacute;nico</strong></p>
            <p>RIOBOOKING podr&aacute; utilizar m&eacute;todos de rastreo electr&oacute;nico (cookies) para personalizar y facilitar al m&aacute;ximo la navegaci&oacute;n del USUARIO por su sitio Web estos m&eacute;todos se asocian &uacute;nicamente a un USUARIO an&oacute;nimo y su ordenador y no proporcionan referencias que permitan deducir datos personales del USUARIO; sin embargo El USUARIO podr&aacute; configurar su navegador para que notifique y rechace la instalaci&oacute;n de las cookies enviadas por RIOBOOKING, sin que ello perjudique la posibilidad del USUARIO de acceder a los contenidos.</p>
            <p><strong>Manejo de links o hiperv&iacute;nculos electr&oacute;nicos:</strong></p>
            <p>En el caso de que en el sitio web se dispusiesen enlaces o hiperv&iacute;nculos hac&iacute;a otros sitios de Internet, RIOBOOKING no ejercer&aacute; ning&uacute;n tipo de control sobre dichos sitios y contenidos. En ning&uacute;n caso RIOBOOKING asumir&aacute; responsabilidad alguna por los contenidos de alg&uacute;n enlace perteneciente a un sitio web ajeno, ni garantizar&aacute; la disponibilidad t&eacute;cnica, calidad, fiabilidad, exactitud, amplitud, veracidad, validez y constitucionalidad de cualquier material o informaci&oacute;n contenida en ninguno de dichos hiperv&iacute;nculos u otros sitios de Internet. Igualmente, la inclusi&oacute;n de estas conexiones externas no implicar&aacute; ning&uacute;n tipo de asociaci&oacute;n, fusi&oacute;n o participaci&oacute;n con las entidades conectadas.</p>
            <p>​Cap&iacute;tulo IV. Derechos de los Usuarios</p>
            <p>​​Los Derechos de los USUARIOS son:</p>
            <p>​​​&bull; ​Conocer, actualizar y rectificar sus datos personales frente a RIOBOOKING. Este derecho se podr&aacute; ejercer, entre otros frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo Tratamiento est&eacute; expresamente prohibido o no haya sido autorizado.</p>
            <p>​&bull; ​Solicitar prueba de la autorizaci&oacute;n otorgada a RIOBOOKING salvo cuando expresamente se except&uacute;e como requisito para el Tratamiento, de conformidad con lo previsto en el art&iacute;culo 10 de la ley 1581 del 2012.​</p>
            <p>​&bull; ​Ser informado por RIOBOOKING, previa solicitud, respecto del uso que le ha dado o le dar&aacute; a sus datos personales.​</p>
            <p>​&bull; ​Presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la ley 1581 de 2012 y las dem&aacute;s normas que la modifiquen, adicionen o complementen.​</p>
            <p>​&bull; ​Revocar la autorizaci&oacute;n y/o solicitar la supresi&oacute;n del dato cuando en el Tratamiento no se respeten los principios, derechos y garant&iacute;as constitucionales y legales. La revocatoria y/o supresi&oacute;n proceder&aacute; cuando la Superintendencia de Industria y Comercio haya determinado que RIOBOOKING han incurrido en conductas contrarias a la ley 1581 de 2012 y a la Constituci&oacute;n.​</p>
            <p>​&bull; ​Acceder en forma gratuita a sus datos personales que hayan sido objeto de Tratamiento.​</p>
            <p>​&nbsp;Cap&iacute;tulo V. Deberes de RIOBOOKING</p>
            <p>​RIOBOOKING se compromete a cumplir los siguientes deberes, sin perjuicio de las dem&aacute;s disposiciones previstas en la ley 1581 del 2012 y en otras que rijan su actividad:</p>
            <p>​&bull; ​Garantizar a los USUARIOS, en todo tiempo, el pleno y efectivo ejercicio del derecho de h&aacute;beas data.</p>
            <p>​&bull; ​Conservar la informaci&oacute;n bajo las condiciones de seguridad necesarias para impedir su adulteraci&oacute;n, p&eacute;rdida, consulta, uso o acceso no autorizado o fraudulento.</p>
            <p>​&bull; ​Realizar oportunamente la actualizaci&oacute;n, rectificaci&oacute;n o supresi&oacute;n de los datos en los t&eacute;rminos de la ley 1581 del 2012.</p>
            <p>​&bull; ​Actualizar la informaci&oacute;n reportada dentro de los diez (10) d&iacute;as h&aacute;biles contados a partir de su recibo.</p>
            <p>​&bull; ​Tramitar las consultas y los reclamos formulados por los USUARIOS en los t&eacute;rminos se&ntilde;alados en la ley 1581 de 2012.</p>
            <p>​&bull; ​Adoptar un manual interno de pol&iacute;ticas y procedimientos para garantizar el adecuado cumplimiento de la ley 1581 del 2012 y, en especial, para la atenci&oacute;n de consultas y reclamos por parte de los USUARIOS.</p>
            <p>​&bull; ​Registrar en la base de datos la leyenda "reclamo en tr&aacute;mite" en la forma en que se regula en la ley 1581 del 2012.​​</p>
            <p>​&bull; ​Insertar en la base de datos la leyenda "informaci&oacute;n en discusi&oacute;n judicial" una vez notificado por parte de la autoridad competente sobre procesos judiciales relacionados con la calidad del dato personal.</p>
            <p>​&bull; ​Abstenerse de circular informaci&oacute;n que est&eacute; siendo controvertida por los USUARIOS y cuyo bloqueo haya sido ordenado por la Superintendencia de Industria y Comercio.</p>
            <p>​&bull; ​Permitir el acceso a la informaci&oacute;n &uacute;nicamente a las personas que pueden tener acceso a ella.</p>
            <p>​&bull; ​Informar a la Superintendencia de Industria y Comercio cuando se presenten violaciones a los c&oacute;digos de seguridad y existan riesgos en la administraci&oacute;n de la informaci&oacute;n de los USUARIOS.</p>
            <p>​&bull; ​Cumplir las instrucciones y requerimientos que imparta la Superintendencia de Industria y Comercio.</p>
            <p>​Cap&iacute;tulo VI. Canal de Atenci&oacute;n</p>
            <p>RIOBOOKING designa al coordinador de Seguridad de la Informaci&oacute;n, en adici&oacute;n a sus otras funciones, para cumplir la funci&oacute;n de protecci&oacute;n de datos personales y para dar tr&aacute;mite a las solicitudes de los USUARIOS, para el ejercicio de los derechos de acceso, consulta, rectificaci&oacute;n, actualizaci&oacute;n, supresi&oacute;n y revocatoria a que se refiere la Ley 1581 de 2012.</p>
            <p>En caso de presentarse cualquiera requerimiento, petici&oacute;n, queja, reclamo o consulta referente al ejercicio de sus derechos de usuario o cliente podr&aacute; comunicarse al correo electr&oacute;nico segurinfo@coem.co, en el link de cont&aacute;ctenos de la p&aacute;gina web o a las siguientes direcciones f&iacute;sicas: Carrera 16 N&deg; 75 &ndash; 50​&nbsp;Bogot&aacute; Colombia Tel: 057- 546 2727, en horario de oficina de 8.00 am a 5.00 pm.​</p>
            <p>​Cap&iacute;tulo VII. Atenci&oacute;n de peticiones, consultas y reclamos de los usuarios</p>
            <p>​El USUARIO tiene derecho a acceder a sus datos personales y a los detalles del tratamiento de los mismos, as&iacute; como a rectificarlos o actualizarlos en caso de ser inexactos, tambi&eacute;n podr&aacute; solicitar su eliminaci&oacute;n cuando considere que resulten ser excesivos o innecesarios para las finalidades que justificaron su obtenci&oacute;n u oponerse al tratamiento de los mismos para fines espec&iacute;ficos. El USUARIO podr&aacute; acceder en forma gratuita a sus datos personales que hayan sido objeto de Tratamiento por parte de RIOBOOKING.</p>
            <p><strong>Consultas</strong></p>
            <p>De conformidad con lo establecido en el art&iacute;culo 14 de la Ley 1581 de 2012 los USUARIOS podr&aacute;n consultar la informaci&oacute;n personal que repose en cualquier base de datos. En consecuencia, RIOBOOKING garantizar&aacute; el derecho de consulta, suministrando a los USUARIOS, toda la informaci&oacute;n contenida en el registro individual o que est&eacute; vinculada con la identificaci&oacute;n del usuario.</p>
            <p>Para la atenci&oacute;n de solicitudes de consulta de datos personales RIOBOOKING garantiza:</p>
            <p>​&bull; ​Habilitaci&oacute;n de medios de comunicaci&oacute;n electr&oacute;nica u otros que considere pertinentes para atender las consultas.</p>
            <p>​&bull; ​Implementaci&oacute;n de formularios, sistemas y otros m&eacute;todos simplificados para atender las consultas, mismos que deben ser informados en el aviso de privacidad.</p>
            <p>​&bull; ​Utilizar los servicios de atenci&oacute;n al cliente o de reclamaciones que tiene en operaci&oacute;n.</p>
            <p>En cualquier caso, independientemente del mecanismo implementado para la atenci&oacute;n de solicitudes de consulta, las mismas ser&aacute;n atendidas en un t&eacute;rmino m&aacute;ximo de diez (10) d&iacute;as h&aacute;biles contados a partir de la fecha de su recibo. Cuando no fuere posible atender la consulta dentro de dicho t&eacute;rmino, se informar&aacute; al interesado antes del vencimiento de los diez (10) d&iacute;as, expresando los motivos de la demora y se&ntilde;alando la fecha en que se atender&aacute; su consulta, la cual en ning&uacute;n caso podr&aacute; superar los cinco (5) d&iacute;as h&aacute;biles siguientes al vencimiento del primer plazo.</p>
            <p><strong>Reclamos</strong></p>
            <p>De conformidad con lo establecido en el art&iacute;culo 14 de la Ley 1581 de 2012, el USUARIOS que consideren que la informaci&oacute;n contenida en una base de datos debe ser objeto de correcci&oacute;n, actualizaci&oacute;n o supresi&oacute;n, o cuando adviertan el presunto incumplimiento de cualquiera de los deberes contenidos en la Ley 1581 de 2012, podr&aacute;n presentar un reclamo ante el Responsable del Tratamiento, el cual ser&aacute; tramitado bajo las siguientes reglas:</p>
            <p>​&bull; ​El reclamo lo podr&aacute; presentar el usuario en los formatos que al efecto presente RIOBOOKING en su p&aacute;gina web. Si el reclamo recibido no cuenta con informaci&oacute;n completa que permita darle tr&aacute;mite, esto es, con la identificaci&oacute;n del usuario, la descripci&oacute;n de los hechos que dan lugar al reclamo, la direcci&oacute;n, y acompa&ntilde;ando los documentos que se quiera hacer valer, se requerir&aacute; al interesado dentro de los cinco (5) d&iacute;as siguientes a su recepci&oacute;n para que subsane las fallas. Transcurridos dos (2) meses desde la fecha del requerimiento sin que el solicitante presente la informaci&oacute;n requerida, se entender&aacute; que ha desistido del reclamo, si por alguna circunstancia RIOBOOKING recibe un reclamo que en realidad no deber&iacute;a ir dirigido contra &eacute;l, dar&aacute; traslado a quien corresponda en un t&eacute;rmino m&aacute;ximo de cinco (5) d&iacute;as h&aacute;biles e informar&aacute; de la situaci&oacute;n al interesado o usuario.</p>
            <p>​&bull; ​Una vez recibido el reclamo completo, se incluir&aacute; en la base de datos que mantiene RIOBOOKING una leyenda que diga "reclamo en tr&aacute;mite" y el motivo del mismo, en un t&eacute;rmino no mayor a dos (2) d&iacute;as h&aacute;biles. Dicha leyenda deber&aacute; mantenerse hasta que el reclamo sea decidido.</p>
            <p>​&bull; ​El t&eacute;rmino m&aacute;ximo para atender el reclamo ser&aacute; de quince (15) d&iacute;as h&aacute;biles contados a partir del d&iacute;a siguiente a la fecha de su recibo. Cuando no fuere posible atenderlo dentro de dicho t&eacute;rmino se informar&aacute; al interesado antes del vencimiento del referido plazo los motivos de la demora y la fecha en que se atender&aacute; su reclamo, la cual en ning&uacute;n caso podr&aacute; superar los ocho (8) d&iacute;as h&aacute;biles siguientes al vencimiento del primer t&eacute;rmino.</p>
            <ul>
                <li>​ ​En cualquier momento y de manera gratuita el usuario o su representante podr&aacute;n solicitar a RIOBOOKING la rectificaci&oacute;n, actualizaci&oacute;n o supresi&oacute;n de sus datos personales, previa acreditaci&oacute;n de su identidad.</li>
            </ul>
            <p>​</p>
            <p><strong>Rectificaci&oacute;n y Actualizaci&oacute;n de Datos</strong></p>
            <p>RIOBOOKING tiene la obligaci&oacute;n de rectificar y actualizar a solicitud de los USUARIOS, la informaci&oacute;n de &eacute;ste que resulte ser incompleta o inexacta, de conformidad con el procedimiento y los t&eacute;rminos arriba se&ntilde;alados. Al respecto se tendr&aacute; en cuenta lo siguiente:</p>
            <ul>
                <li>​ ​En las solicitudes de rectificaci&oacute;n y actual​izaci&oacute;n de datos personales los USUARIOS debe indicar las correcciones a realizar y aportar la documentaci&oacute;n que avale su petici&oacute;n.</li>
            </ul>
            <p>​&bull; ​RIOBOOKING tiene plena libertad de habilitar mecanismos que le faciliten el ejercicio de este derecho, siempre y cuando &eacute;stos beneficien al USUARIO. En consecuencia, se podr&aacute;n habilitar medios electr&oacute;nicos u otros que considere pertinentes.</p>
            <p>​&bull; ​RIOBOOKING podr&aacute; establecer formularios, sistemas y otros m&eacute;todos simplificados, mismos que deben ser informados en el aviso de privacidad y que se pondr&aacute;n a disposici&oacute;n de los interesados en la p&aacute;gina web.</p>
            <p>​&nbsp;</p>
            <p><strong>Supresi&oacute;n de Datos</strong></p>
            <p>Lo USUARIOS tiene el derecho, en todo momento, a solicitar RIOBOOKING la supresi&oacute;n (eliminaci&oacute;n) de sus datos personales cuando:</p>
            <p>​&bull; ​Considere que los mismos no est&aacute;n siendo tratados conforme a los principios, deberes y obligaciones previstas en la Ley 1581 de 2012.</p>
            <p>​&bull; ​Hayan dejado de ser necesarios o pertinentes para la finalidad para la cual fueron recabados.</p>
            <p>​&bull; ​Se haya superado el periodo necesario para el cumplimiento de los fines para los que fueron capturados.</p>
            <p>​&bull; ​Esta supresi&oacute;n implica la eliminaci&oacute;n total o parcial de la informaci&oacute;n personal de acuerdo con lo solicitado por los USUARIOS en los registros, archivos, bases de datos o tratamientos realizados por RIOBOOKING.</p>
            <p>RIOBOOKING puede negar el ejercicio del derecho de supresi&oacute;n cuando:</p>
            <p>​&bull; ​Los USUARIOS tenga un deber legal o contractual de permanecer en la base de datos de RIOBOOKING.</p>
            <p>​&bull; ​La eliminaci&oacute;n de datos obstaculice actuaciones judiciales o administrativas vinculadas a obligaciones fiscales, la investigaci&oacute;n y persecuci&oacute;n de delitos o la actualizaci&oacute;n de sanciones administrativas.</p>
            <p>​&bull; ​Los datos sean necesarios para proteger los intereses jur&iacute;dicamente tutelados del USUARIO; para realizar una acci&oacute;n en funci&oacute;n del inter&eacute;s p&uacute;blico, o para cumplir con una obligaci&oacute;n legalmente adquirida por los USUARIOS.</p>
            <p>​&bull; ​En caso de resultar procedente la cancelaci&oacute;n de los datos personales, RIOBOOKING debe realizar operativamente la supresi&oacute;n de tal manera que la eliminaci&oacute;n no permita la recuperaci&oacute;n de la informaci&oacute;n.</p>
            <p>​&nbsp;</p>
            <p><strong>Revocatoria de la Autorizaci&oacute;n de consentimiento</strong></p>
            <p>Los USUARIOS de los datos personales pueden revocar el consentimiento al tratamiento de sus datos personales en cualquier momento, siempre y cuando no lo impida una disposici&oacute;n legal. Para ello, el usuario debe notificar su decisi&oacute;n por escrito a RIOBOOKING quien proceder&aacute; de la siguiente manera:&nbsp;</p>
            <p>​&bull; ​Si es Revocatoria Total de la Autorizaci&oacute;n: Es sobre la totalidad de las finalidades consentidas, esto es, que RIOBOOKING deba dejar de tratar por completo los datos del usuario y borrar todos sus registros, no obstante, debe conservar la autorizaci&oacute;n y la solicitud de revocatoria de la misma.</p>
            <p>​&bull; ​Si es Revocatoria Parcial de la Autorizaci&oacute;n: Es con una finalidad especial, por ejemplo, para publicidad, o estudios de mercado, etc., pero se mantienen a salvo otros fines, RIOBOOKING deber&aacute; borrar y no usar los datos del usuario para las finalidades restringidas, de conformidad con la autorizaci&oacute;n otorgada.​</p>
            <p>Entonces, los USUARIOS deber&aacute;n solicitar por escrito la revocatoria del de consentimiento a RIOBOOKING indicando si la revocatoria es total o parcial y en este &uacute;ltimo caso cual es el tratamiento no conforme.</p>
            <p>Los mecanismos o procedimientos que RIOBOOKING se establezca para atender las solicitudes de revocatoria del consentimiento no podr&aacute;n exceder de 15 d&iacute;as h&aacute;biles contados a partir del d&iacute;a siguiente de su recibo o del momento en que este completa la informaci&oacute;n para proceder al tr&aacute;mite solicitado.</p>
            <p>​Cap&iacute;tulo VIII. Vigencia, modificaci&oacute;n y versionamiento y prohibici&oacute;n de uso</p>
            <p>​Este documento de pol&iacute;tica y procedimiento de protecci&oacute;n de datos personales est&aacute; fundamentado en las disposiciones contenidas en los art&iacute;culos 15 y 20 de la Constituci&oacute;n Pol&iacute;tica y por la Ley 1581 de 2012 "Por la cual se dictan disposiciones generales para la protecci&oacute;n de datos personales". Por tanto, este documento aplica al tratamiento de los datos de car&aacute;cter personal que registre y maneje RIOBOOKING. Los USUARIOS aceptan y reconocen que esta autorizaci&oacute;n estar&aacute; vigente a partir del momento en que la acept&oacute;, y durante el tiempo en que RIOBOOKING desarrolle las actividades propias de su objeto social.</p>
            <p>RIOBOOKING puede cambiar unilateralmente su pol&iacute;tica de privacidad y de uso de datos personales cuando as&iacute; lo requiera sin el expreso consentimiento del USUARIO, pero se obliga a conservar las versiones anteriores de la presente pol&iacute;tica de privacidad y de uso de datos personales, si las hubiere y a garantizar los derechos de los USUARIOS que emanan de la Constituci&oacute;n y la Ley Colombiana.</p>
            <p><strong>Nota de Vigencia.</strong>&nbsp;El presente documento de pol&iacute;tica de tratamiento de informaci&oacute;n y datos personales &ndash; versi&oacute;n 1, est&aacute; vigente y rige a partir del veintisiete (27) de Mayo de dos mil veinte (2020).​</p>


    </div>

    </div>
    <!-- /white_bg -->

@endsection
